.PHONY: clean clean_tox compile_translations coverage diff_cover docs dummy_translations \
        extract_translations fake_translations help pii_check pull_translations push_translations \
        quality requirements selfcheck test test-all upgrade validate install_transifex_client

.DEFAULT_GOAL := help

# For opening files in a browser. Use like: $(BROWSER)relative/path/to/file.html
BROWSER := python -m webbrowser file://$(CURDIR)/

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	uv run coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

clean_tox: ## clear tox requirements cache
	rm -fr .tox

coverage: clean ## generate and view HTML coverage report
	uv run pytest --cov-report html
	$(BROWSER)htmlcov/index.html

docs: ## generate Sphinx HTML documentation, including API docs
	uv run doc8 --ignore-path docs/_build README.rst docs
	rm -f docs/platform_plugin_aspects.rst
	rm -f docs/modules.rst
	make -e -C docs clean
	make -e -C docs html
	$(BROWSER)docs/_build/html/index.html

upgrade: ## update python dependencies
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

quality: ## check coding style with pycodestyle and pylint
	uv run pylint src/platform_plugin_aspects test_utils manage.py
	uv run pycodestyle src/platform_plugin_aspects manage.py
	uv run pydocstyle src/platform_plugin_aspects manage.py
	uv run isort --check-only --diff test_utils src/platform_plugin_aspects manage.py
	uv run black --check --diff src/platform_plugin_aspects test_utils manage.py
	make selfcheck

pii_check: ## check for PII annotations on all Django models
	uv run code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage

requirements: ## install development environment requirements
	uv sync --group dev
	uv tool install tox --with tox-uv

test: clean ## run tests in the current virtualenv
	uv run python manage.py check
	uv run pytest --full-trace

diff_cover: test ## find diff lines that need test coverage
	uv run diff-cover coverage.xml

format:
	uv run isort src/platform_plugin_aspects
	uv run black .

test-all: quality pii_check ## run tests on every supported Python/Django combination
	uv run tox
	uv run tox -e docs

validate: quality pii_check test ## run tests and quality checks

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

## Localization targets

extract_translations: ## extract strings to be translated, outputting .mo files
	rm -rf docs/_build
	cd src/platform_plugin_aspects && django-admin makemessages -l en -v1 -d django
	cd src/platform_plugin_aspects && django-admin makemessages -l en -v1 -d djangojs

compile_translations: ## compile translation files, outputting .po files for each supported language
	cd src/platform_plugin_aspects && i18n_tool generate

detect_changed_source_translations:
	cd src/platform_plugin_aspects && i18n_tool changed

ifeq ($(OPENEDX_ATLAS_PULL),)
pull_translations: ## Pull translations from Transifex
	tx pull -t -a -f --mode reviewed --minimum-perc=1
else
# Experimental: OEP-58 Pulls translations using atlas
pull_translations:
	find src/platform_plugin_aspects/conf/locale -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
	atlas pull $(OPENEDX_ATLAS_ARGS) translations/platform-plugin-aspects/platform_plugin_aspects/conf/locale:src/platform_plugin_aspects/conf/locale
	uv run python manage.py compilemessages

	@echo "Translations have been pulled via Atlas and compiled."
endif

push_translations: ## push source translation files (.po) from Transifex
	tx push -s

dummy_translations: ## generate dummy translation (.po) files
	cd src/platform_plugin_aspects && i18n_tool dummy

build_dummy_translations: extract_translations dummy_translations compile_translations ## generate and compile dummy translation files

validate_translations: build_dummy_translations detect_changed_source_translations ## validate translations

install_transifex_client: ## Install the Transifex client
	# Instaling client will skip CHANGELOG and LICENSE files from git changes
	# so remind the user to commit the change first before installing client.
	git diff -s --exit-code HEAD || { echo "Please commit changes first."; exit 1; }
	curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
	git checkout -- LICENSE README.md ## overwritten by Transifex installer
