name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call: # allows release.yml to call this as a reusable workflow

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        toxenv: [quality, docs, pii_check, django52]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Run tox
        run: uv run tox -e ${{ matrix.toxenv }}
